kind: pipeline
name: default
type: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: push github mirror
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote: git@github.com:fmnx-su/iso.git
      force: true
      commit: true
      ssh_key:
        from_secret: SSHKEY

  - name: push codeberg mirror
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote: git@codeberg.org:fmnx/iso.git
      force: true
      commit: true
      ssh_key:
        from_secret: SSHKEY
