install-scripts:
  - sed -i 's|<USER>|<AINST=USER>|g' /root/creds.json
  - sed -i 's|<PASS>|<AINST=PASS>|g' /root/creds.json
  - sed -i 's|<DISK>|<AINST=DISK>|g' /root/disk.json
  - sed -i 's|<USER>|<AINST=USER>|g' .gitconfig
  - sed -i 's|<EMAIL>|<AINST=EMAIL>|g' .gitconfig
  - sed -i 's|<DISK>|<AINST=DISK>|g' /root/config.json
  - sed -i 's|<GFXDRIVER>|<AINST=GFXDRIVER>|g' /root/config.json
  - sed -i 's|<USER>|<AINST=USER>|g' /root/config.json
  - sed -i 's|<KBLAYOUT>|<AINST=KBLAYOUT>|g' /root/config.json
  - sed -i 's|<SYSLANG>|<AINST=SYSLANG>|g' /root/config.json
  - sed -i 's|<TIMEZONE>|<AINST=TIMEZONE>|g' /root/config.json
  - archinstall --silent --disk_layouts /root/disk.json --config /root/config.json --creds /root/creds.json
  - cp /etc/os-release /mnt/archinstall/etc/os-release
  - cp /etc/pacman.conf /mnt/archinstall/etc/pacman.conf
  - mkdir -p /mnt/archinstall/etc/dconf/profile
  - cp /etc/dconf/profile/user /mnt/archinstall/etc/dconf/profile/user
  - mkdir -p /mnt/archinstall/etc/dconf/db/local.d
  - cp /etc/dconf/db/local.d/00-settings /mnt/archinstall/etc/dconf/db/local.d/00-settings
  - mkdir -p /mnt/archinstall/etc/dconf/profile
  - cp /etc/dconf/profile/user /mnt/archinstall/etc/dconf/profile/user
  - mkdir -p /mnt/archinstall/usr/local/share/backgrounds
  - cp /usr/local/share/backgrounds/wallpaper.jpg /mnt/archinstall/usr/local/share/backgrounds/wallpaper.jpg
  - cp /usr/local/share/backgrounds/fmnx-linux.png /mnt/archinstall/usr/local/share/backgrounds/fmnx-linux.png
  - arch-chroot /mnt/archinstall dconf update
  - sed -i "s|/bin/bash|/usr/bin/zsh|g" /mnt/archinstall/etc/passwd
  - sed -i "s/3/0/g" /mnt/archinstall/boot/loader/loader.conf
  - cp /usr/onlyoffice-desktopeditors.desktop /mnt/archinstall/usr/share/applications/onlyoffice-desktopeditors.desktop
  - chmod a+rwx /mnt/archinstall/usr/share/applications/onlyoffice-desktopeditors.desktop
  - arch-chroot /mnt/archinstall xdg-icon-resource install --novendor --size 512 /usr/local/share/backgrounds/fmnx-linux.png
  - echo 'export GOPATH=$HOME/go' >> .zshrc
  - echo 'export PATH=$PATH:$(go env GOPATH)/bin' >> .zshrc
  - echo 'export PATH=$PATH:$HOME/.pub-cache/bin' >> .zshrc
  - rm /root/config.json
  - rm /root/disk.json
  - rm /root/creds.json
  - rm /root/.ainst.yml
  - rm /root/.automated_script.sh
  - rm /root/.config/autostart/ainst.desktop
  - cp -a /root/. /mnt/archinstall/home/<AINST=USER>
  - chmod a+rwx -R /mnt/archinstall/home/<AINST=USER>
  - sed -i "s|Arch|FMNX|g" /mnt/archinstall/boot/loader/entries/**.conf
