install-scripts:
  - sed -i 's|<USER>|<AINST=USER>|g' /root/creds.json
  - sed -i 's|<PASS>|<AINST=PASS>|g' /root/creds.json
  - sed -i 's|<DISK>|<AINST=DISK>|g' /root/disk.json
  - sed -i 's|<USER>|<AINST=USER>|g' /root/.gitconfig
  - sed -i 's|<EMAIL>|<AINST=EMAIL>|g' /root/.gitconfig
  - sed -i 's|<DISK>|<AINST=DISK>|g' /root/config.json
  - sed -i 's|<GFXDRIVER>|<AINST=GFXDRIVER>|g' /root/config.json
  - sed -i 's|<USER>|<AINST=USER>|g' /root/config.json
  - sed -i 's|<KBLAYOUT>|<AINST=KBLAYOUT>|g' /root/config.json
  - sed -i 's|<SYSLANG>|<AINST=SYSLANG>|g' /root/config.json
  - sed -i 's|<TIMEZONE>|<AINST=TIMEZONE>|g' /root/config.json
  - sed -i "s|<USER>|<AINST=USER>|g" /root/.zshrc
  - sed -i "s|<USER>|<AINST=USER>|g" /root/gpg-key-script
  - sed -i "s|<EMAIL>|<AINST=EMAIL>|g" /root/gpg-key-script
  - sed -i "s|<PASS>|<AINST=PASS>|g" /root/gpg-key-script
  - sed -i "s|john@doe.com|<AINST=EMAIL>|g" /etc/makepkg.conf
  - sed -i "s|John Doe|<AINST=USER>|g" /etc/makepkg.conf
  - sed -i "s|#PACKAGER|PACKAGER|g" /etc/makepkg.conf

  - archinstall --silent --disk_layouts /root/disk.json --config /root/config.json --creds /root/creds.json

  - gpg --batch --gen-key gpg-key-script

  - cp /etc/os-release /mnt/archinstall/etc/os-release
  - cp /etc/pacman.conf /mnt/archinstall/etc/pacman.conf
  - cp /etc/makepkg.conf /mnt/archinstall/etc/makepkg.conf
  - sed -i "s|/bin/bash|/usr/bin/zsh|g" /mnt/archinstall/etc/passwd
  - sed -i "s/3/0/g" /mnt/archinstall/boot/loader/loader.conf
  - sed -i "s|Arch|FMNX|g" /mnt/archinstall/boot/loader/entries/**.conf
  - sed -i "s|rootfstype=btrfs|rootfstype=btrfs quiet loglevel=0 systemd.show_status=0|g" /mnt/archinstall/boot/loader/entries/**.conf
  - sed -i "s|root|<AINST=USER>|g" /etc/gdm/custom.conf
  - cp /etc/gdm/custom.conf /mnt/archinstall/etc/gdm/custom.conf

  - arch-chroot /mnt/archinstall pacman -Syu --noconfirm --needed --noprogressbar git bluez-utils dconf-editor chromium nautilus xorg-drivers gedit eog gnome-disk-utility gnome-keyring gnome-logs gnome-system-monitor gnome-shell-extensions gnome-characters gnome-font-viewer gnome-calculator gnome-calendar gnome-clocks gnome-shell-extension-dash-to-dock gnome-shell-extension-compact-top-bar geary deja-dup baobab xdg-user-dirs-gtk papirus-icon-theme ttf-droid adw-gtk-theme zsh-autosuggestions zsh-syntax-highlighting zsh-theme-powerlevel10k docker docker-compose vscodium pack
  - arch-chroot /mnt/archinstall usermod -aG docker <AINST=USER>

  - mkdir -p /mnt/archinstall/etc/dconf/profile
  - cp /etc/dconf/profile/user /mnt/archinstall/etc/dconf/profile/user
  - mkdir -p /mnt/archinstall/etc/dconf/db/local.d
  - cp /etc/dconf/db/local.d/00-settings /mnt/archinstall/etc/dconf/db/local.d/00-settings
  - mkdir -p /mnt/archinstall/etc/dconf/profile
  - cp /etc/dconf/profile/user /mnt/archinstall/etc/dconf/profile/user

  - mkdir -p /mnt/archinstall/usr/local/share/backgrounds
  - cp /usr/local/share/backgrounds/wallpaper.jpg /mnt/archinstall/usr/local/share/backgrounds/wallpaper.jpg
  - cp /usr/local/share/backgrounds/fmnx-linux.png /mnt/archinstall/usr/local/share/backgrounds/fmnx-linux.png
  - arch-chroot /mnt/archinstall xdg-icon-resource install --novendor --size 512 /usr/local/share/backgrounds/fmnx-linux.png
  - arch-chroot /mnt/archinstall dconf update

  - rm /root/config.json
  - rm /root/disk.json
  - rm /root/creds.json
  - rm /root/.ainst.yml
  - rm /root/.automated_script.sh
  - rm /root/.config/autostart/ainst.desktop
  - rm /root/.zlogin
  - cp -a /root/. /mnt/archinstall/home/<AINST=USER>
  - arch-chroot /mnt/archinstall chown -R <AINST=USER> /home/<AINST=USER>
